### ISSUE TITLE
Regression in annotate_sv: error caused by END<POS 

### ISSUE THREAD

**Issue by TBradley27** [epi2me-labs/wf-somatic-variation#28]
### Operating System

Other Linux (please specify below)

### Other Linux

Rocky Linux v8.6

### Workflow Version

v1.2.1

### CLI command run

```
/scratchc/jblab/nextflow run epi2me-labs/wf-somatic-variation \
        -c my_config.cfg \
        -resume \
        -profile 'singularity' \
        --mod \
        --snv \
        --sv \
        --sample_name 'foo' \
        --ref '/scratchc/bioinformatics/reference_data/reference_genomes/homo_sapiens/GRCh38_hs38d1/fasta/hsa.GRCh38_hs38d1.fa' \
        --bam_normal '/scratchc/jblab/bradle02/ONT/ONT_alignment/results/bam/PAQ54249/PAQ54249.sorted.bam' \
        --bam_tumor '/scratchc/jblab/bradle02/ONT/ONT_alignment/results/bam/ONT_040/ONT_040.sorted.bam' \
        --basecaller_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.2.0'
 ```

### Workflow Execution - CLI Execution Profile

None

### What happened?

We are getting errors due to END<POS

This was reported as fixed for the v0.5.0 release (https://github.com/epi2me-labs/wf-somatic-variation/releases/tag/v0.5.0). This is the relevant commit:

https://github.com/epi2me-labs/wf-somatic-variation/commit/787084c0349f035657dad8f21ba538713ae3805f

However,

I think when severus was swapped for nanomonsv - this filter is no longer implemented, leading to errors.

This is also related to the following discussion point:

https://github.com/KolmogorovLab/Severus/issues/11

### Relevant log output

```shell
Command error:
  Picked up JAVA_TOOL_OPTIONS: -Xlog:disable -Xlog:all=warning:stderr
  VcfFileIterator.parseVcfLine(133):    Fatal error reading file 'input.vcf.gz' (line: 3555):
  chr12 31601499        severus_INV2850 N       <INV>   60      PASS    IMPRECISE;SVTYPE=INV;SVLEN=173;CHR2=chr12;END=31601326;STRANDS=++;DETAILED_TYPE=.;MAPQ=60;CLUSTERID=severus_6   GT:GQ:VAF:hVAF:DR:DV    0/0:959:0.05:1,0,0:79:4
  java.lang.RuntimeException: java.lang.RuntimeException: INFO field 'END' is before varaint's 'POS'
        END : 31601325
        POS : 31601498
        at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:134)
        at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:185)
        at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:58)
        at org.snpeff.fileIterator.FileIterator.hasNext(FileIterator.java:123)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:473)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:139)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:918)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:875)
        at org.snpeff.SnpEff.run(SnpEff.java:1141)
        at org.snpeff.SnpEff.main(SnpEff.java:160)
  Caused by: java.lang.RuntimeException: INFO field 'END' is before varaint's 'POS'
        END : 31601325
        POS : 31601498
        at org.snpeff.vcf.VcfEntry.parseEnd(VcfEntry.java:1187)
        at org.snpeff.vcf.VcfEntry.parse(VcfEntry.java:1027)
        at org.snpeff.vcf.VcfEntry.<init>(VcfEntry.java:247)
        at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:131)
        ... 9 more
```
```

**Comment by RenzoTale88** [comment]
@TBradley27 thanks for letting us know about this, we are working on a patch

**Comment by RenzoTale88** [comment]
This should be fixed in v1.3.0. @TBradley27 could you please check that the new release completes the run successfully?

**Comment by TBradley27** [comment]
Hi @RenzoTale88 , I can confirm that this problem is fixed now

**Comment by Soniazumalave** [comment]
Hi! I am using version: v1.4.0-g81de957, and get the same problem.

**Comment by Soniazumalave** [comment]
Hi! I am using version: v1.4.0-g81de957, and get the same problem (Severus coordinates bug END<POS) in multiple samples. Any advice on how to fix it? Many thanks.

## My command 
```nextflow run epi2me-labs/wf-somatic-variation \
	--snv \
	--sv \
	--mod \
	--sample_name ${donor_id}_${tumour_id} \
	--ref $ref \
	--bam_normal $normal_bam_dir \
	--bam_tumor $tumour_bam_dir \
	--normal_min_coverage 15 \
	--tumor_min_coverage 20 \
	--phase_normal \
	-profile singularity \
    -c ${config} \
	-resume
```

## Relevant log output
```VcfFileIterator.parseVcfLine(133):	Fatal error reading file 'input.vcf.gz' (line: 2215):
  chr11	81812793	severus_DUP1469	N	<DUP>	60	PASS	PRECISE;SVTYPE=DUP;SVLEN=177;END=81812616;STRANDS=-+;DETAILED_TYPE=tandem_duplication;MAPQ=60	GT:GQ:VAF:hVAF:DR:DV	0/0:1227:0.03:0.03,0,0:100:3
  java.lang.RuntimeException: java.lang.RuntimeException: INFO field 'END' is before varaint's 'POS'
  	END : 81812615
  	POS : 81812792
  	at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:134)
  	at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:185)
  	at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:58)
  	at org.snpeff.fileIterator.FileIterator.hasNext(FileIterator.java:123)
  	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:473)
  	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:139)
  	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:918)
  	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:875)
  	at org.snpeff.SnpEff.run(SnpEff.java:1141)
  	at org.snpeff.SnpEff.main(SnpEff.java:160)
  Caused by: java.lang.RuntimeException: INFO field 'END' is before varaint's 'POS'
  	END : 81812615
  	POS : 81812792
  	at org.snpeff.vcf.VcfEntry.parseEnd(VcfEntry.java:1187)
  	at org.snpeff.vcf.VcfEntry.parse(VcfEntry.java:1027)
  	at org.snpeff.vcf.VcfEntry.<init>(VcfEntry.java:247)
  	at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:131)
  	... 9 more
```

**Comment by TBradley27** [comment]
Hi Sonia,

Apologies for the delay. I have just seen this

I know why this isn't working for you.

The relevant commit is https://github.com/epi2me-labs/wf-somatic-variation/commit/3f00ca71fe175c5e99d6d6309d2d920e0ce97ec4.

This commit only fixes this problem when SV type = INV. Your SV type = DUP, and so the fix doesn't catch this.

I have reopened the issue as I agree the current pipeline behaviour is still problematic
