### ISSUE TITLE
Error executing process > 'ingress_tumor:checkBamHeaders (1)'

### ISSUE THREAD

**Issue by Manoswini-02** [epi2me-labs/wf-somatic-variation#29]
### Ask away!

I'm attempting to execute wf-somatic-variation on the cluster, but it's throwing an error: "Error executing process > 'ingress_tumor (1)'".
As the error code suggests no BGZF EOF marker; file may be truncated, I verified the BAM files using samtools, and they appeared to be intact. I am using the same bam files for other analysis (wf-human-variation) and it worked. The data carries modified based calling for both 5mC 5hmC. 

What am I missing? Do I need to look for read group information?

Below is the command: 
`nextflow run epi2me-labs/wf-somatic-variation --bam_normal /lustre/project/skim5/MD/ONT_bam/P2_BAM/ --bam_tumor /lustre/project/skim5/MD/ONT_bam/P28_BAM/ --ref /lustre/project/skim5/MD/ONT_bam/hg38.fa --sv --snv --mod --sample_name P2_P28 --normal_min_coverage 0 --tumor_min_coverage 0 -profile singularity`

### Related log output
ERROR ~ Error executing process > 'ingress_tumor:checkBamHeaders (1)'

Caused by:
  Process `ingress_tumor:checkBamHeaders (1)` terminated with an error exit status (1)

Command executed:

  workflow-glue check_bam_headers_in_dir input_dir > env.vars
  source env.vars
  DS_RUNIDS=$(workflow-glue get_ds_records --xam input_dir --key runid --cardinality zero-or-more --sep ',')
  DS_BASECALL_MODELS=$(workflow-glue get_ds_records --xam input_dir --key basecall_model --cardinality zero-or-one --sep ',' --explode_obviously)

Command exit status:
  1

Command output:
  (empty)

Command error:
  [12:23:07 - workflow_glue] Bootstrapping CLI.
  [12:23:07 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/mdash/.nextflow/assets/epi2me-labs/wf-somatic-variation/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/mdash/.nextflow/assets/epi2me-labs/wf-somatic-variation/bin/workflow_glue/__init__.py", line 82, in cli
      args.func(args)
    File "/home/mdash/.nextflow/assets/epi2me-labs/wf-somatic-variation/bin/workflow_glue/check_bam_headers_in_dir.py", line 31, in main
      with pysam.AlignmentFile(xam_file, check_sq=False) as f:
    File "pysam/libcalignmentfile.pyx", line 748, in pysam.libcalignmentfile.AlignmentFile.__cinit__
    File "pysam/libcalignmentfile.pyx", line 958, in pysam.libcalignmentfile.AlignmentFile._open
    File "pysam/libchtslib.pyx", line 361, in pysam.libchtslib.HTSFile.check_truncation
  OSError: no BGZF EOF marker; file may be truncated_

**Comment by Manoswini-02** [comment]
To update, I was hunting down an error related to something I found in other tools, which hinted at removing the old BAM files. For me, the program started working (it's still running) when I separated it from the other BAM files in the folder, including the sorted ones.

Thanks!
