### ISSUE TITLE
KeyError: 'mod' in workflow_glue/report_mod.py

### ISSUE THREAD

**Issue by lucy924** [epi2me-labs/wf-somatic-variation#35]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.3.1

### Workflow Execution

Command line (Cluster)

### CLI command run

nextflow run epi2me-labs/wf-somatic-variation -params-file params_weka.json -c custom.config -profile singularity -resume

[params_weka.json](https://github.com/user-attachments/files/16791548/params_weka.json)

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

I'm slowly ironing out all the issues in this test run with one pair of samples on chr1, and the latest issue appears to be in the below section of code according to the error:
https://github.com/epi2me-labs/wf-somatic-variation/blob/ba53c64fc63127ffd9ead61e1cc1946557238aae/bin/workflow_glue/report_mod.py#L205

I ran it successfully on the demo data but the demo data run didn't do most of the tumour processing which appears to be the problem here.

Thanks!

### Relevant log output

```shell
--------------------------------------------------------------------------------
Core Nextflow options
  revision           : master
  runName            : extravagant_knuth
  containerEngine    : singularity
  container          : ontresearch/wf-somatic-variation:sha18cc2ea1fae27fc772e7b728957996119c1ec81a
  launchDir          : /weka/dejlu879/BEBIC/CellLineB/wf-sv_B3_CvT/chr1
  workDir            : /weka/dejlu879/BEBIC/CellLineB/wf-sv_B3_CvT/chr1/work
  projectDir         : /home/dejlu879/.nextflow/assets/epi2me-labs/wf-somatic-variation
  userName           : dejlu879
  profile            : singularity
  configFiles        : /home/dejlu879/.nextflow/config, /home/dejlu879/.nextflow/assets/epi2me-labs/wf-somatic-variation/nextflow.config, /weka/dejlu879/BEBIC/CellLineB/wf-sv_B3_CvT/chr1/custom.config

Workflow Options
  mod                : true

Main options
  sample_name        : B3_CvT_chr1
  bam_normal         : /weka/dejlu879/BEBIC/CellLineB/demuxed/chr1/B3_02_Control.bam
  bam_tumor          : /weka/dejlu879/BEBIC/CellLineB/demuxed/chr1/B3_03_Test.bam
  ref                : /weka/dejlu879/refs/hg38_chromsonly_ebv_lambda_bcg/chr1.fa
  out_dir            : /weka/dejlu879/BEBIC/CellLineB/wf-sv_B3_CvT/chr1/output

Quality Control Options
  depth_intervals    : true
  tumor_min_coverage : 15
  normal_min_coverage: 15

Small variant calling options
  fast_mode          : true
  phase_normal       : true

Multiprocessing Options
  ubam_map_threads   : 16
  ubam_sort_threads  : 6
  ubam_bam2fq_threads: 4
  severus_threads    : 16
  dss_threads        : 4
  modkit_threads     : 8

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-somatic-variation for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-somatic-variation v1.3.1-gba53c64.
--------------------------------------------------------------------------------
WARN: Nextflow version 22.10.4 does not match workflow required version: >=23.04.2 -- Execution will continue, but things may break!
[-        ] process > index_ref_fai                      -
[-        ] process > cram_cache                         -
[-        ] process > getVersions                        -
[-        ] process > getVersions_somvar                 -
[-        ] process > getParams                          -
[-        ] process > ingress_normal:checkBamHeaders     -
[-        ] process > ingress_normal:sortBam             -
[33/e06dff] process > index_ref_fai (1)                      [100%] 1 of 1, cached: 1 ✔
[b6/b0d8e4] process > cram_cache (1)                         [100%] 1 of 1, cached: 1 ✔
[16/281675] process > getVersions                            [100%] 1 of 1, cached: 1 ✔
[7f/f005f3] process > getVersions_somvar                     [100%] 1 of 1, cached: 1 ✔
[1b/e32d8e] process > getParams                              [100%] 1 of 1, cached: 1 ✔
[f9/fda36d] process > ingress_normal:checkBamHeaders (1)     [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:sortBam                 -
[33/e06dff] process > index_ref_fai (1)                      [100%] 1 of 1, cached: 1 ✔
[b6/b0d8e4] process > cram_cache (1)                         [100%] 1 of 1, cached: 1 ✔
[16/281675] process > getVersions                            [100%] 1 of 1, cached: 1 ✔
[7f/f005f3] process > getVersions_somvar                     [100%] 1 of 1, cached: 1 ✔
[1b/e32d8e] process > getParams                              [100%] 1 of 1, cached: 1 ✔
[f9/fda36d] process > ingress_normal:checkBamHeaders (1)     [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:sortBam                 -
executor >  slurm (1)
[33/e06dff] process > index_ref_fai (1)                      [100%] 1 of 1, cached: 1 ✔
[b6/b0d8e4] process > cram_cache (1)                         [100%] 1 of 1, cached: 1 ✔
[16/281675] process > getVersions                            [100%] 1 of 1, cached: 1 ✔
[7f/f005f3] process > getVersions_somvar                     [100%] 1 of 1, cached: 1 ✔
[1b/e32d8e] process > getParams                              [100%] 1 of 1, cached: 1 ✔
[f9/fda36d] process > ingress_normal:checkBamHeaders (1)     [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:sortBam                 -
executor >  slurm (1)
[33/e06dff] process > index_ref_fai (1)                      [100%] 1 of 1, cached: 1 ✔
[b6/b0d8e4] process > cram_cache (1)                         [100%] 1 of 1, cached: 1 ✔
[16/281675] process > getVersions                            [100%] 1 of 1, cached: 1 ✔
[7f/f005f3] process > getVersions_somvar                     [100%] 1 of 1, cached: 1 ✔
[1b/e32d8e] process > getParams                              [100%] 1 of 1, cached: 1 ✔
[f9/fda36d] process > ingress_normal:checkBamHeaders (1)     [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:sortBam                 -
executor >  slurm (1)
[33/e06dff] process > index_ref_fai (1)                      [100%] 1 of 1, cached: 1 ✔
[b6/b0d8e4] process > cram_cache (1)                         [100%] 1 of 1, cached: 1 ✔
[16/281675] process > getVersions                            [100%] 1 of 1, cached: 1 ✔
[7f/f005f3] process > getVersions_somvar                     [100%] 1 of 1, cached: 1 ✔
[1b/e32d8e] process > getParams                              [100%] 1 of 1, cached: 1 ✔
[f9/fda36d] process > ingress_normal:checkBamHeaders (1)     [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:sortBam                 -
[-        ] process > ingress_normal:mergeBams               -
[-        ] process > ingress_normal:catSortBams             -
[c9/829b50] process > ingress_normal:validateIndex (1)       [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:samtools_index          -
[8c/4a0972] process > ingress_normal:check_for_alignment (1) [100%] 1 of 1, cached: 1 ✔
[93/d9af88] process > ingress_normal:minimap2_alignment (1)  [100%] 1 of 1, cached: 1 ✔
[e8/a8c58e] process > ingress_tumor:checkBamHeaders (1)      [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_tumor:sortBam                  -
[-        ] process > ingress_tumor:mergeBams                -
[-        ] process > ingress_tumor:catSortBams              -
[54/5c8f0e] process > ingress_tumor:validateIndex (1)        [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_tumor:samtools_index           -
[44/d402d9] process > ingress_tumor:check_for_alignment (1)  [100%] 1 of 1, cached: 1 ✔
[17/37132c] process > ingress_tumor:minimap2_alignment (1)   [100%] 1 of 1, cached: 1 ✔
[73/228f6c] process > getGenome (1)                          [100%] 2 of 2, cached: 2 ✔
[c9/37fb0e] process > getAllChromosomesBed (1)               [100%] 1 of 1, cached: 1 ✔
[c6/aaefbf] process > alignment_stats:bamstats (2)           [100%] 2 of 2, cached: 2 ✔
[af/c30e2f] process > alignment_stats:mosdepth (2)           [100%] 2 of 2, cached: 2 ✔
[ad/5806b9] process > alignment_stats:makeQCreport (1)       [100%] 1 of 1, cached: 1 ✔
[7e/239141] process > get_coverage (2)                       [100%] 2 of 2, cached: 2 ✔
[f6/cc58c7] process > publish_qc (17)                        [100%] 17 of 17, cached: 17 ✔
[a2/e1f00a] process > mod:validate_modbam (1)                [100%] 2 of 2, cached: 2 ✔
[e4/b17c10] process > mod:sample_probs (1)                   [100%] 2 of 2, cached: 2 ✔
[98/a88384] process > mod:modkit (1)                         [100%] 2 of 2, cached: 2 ✔
[6e/542e42] process > mod:concat_bedmethyl (1)               [100%] 2 of 2, cached: 2 ✔
[84/17f625] process > mod:bedmethyl_split (2)                [100%] 2 of 2, cached: 2 ✔
[4f/15beff] process > mod:summary (2)                        [100%] 2 of 2, cached: 2 ✔
[96/222728] process > mod:bed2dss (6)                        [100%] 6 of 6, cached: 6 ✔
[7c/db7931] process > mod:dss (3)                            [100%] 3 of 3, cached: 3 ✔
[fd/15c0b6] process > mod:getVersions                        [100%] 1 of 1, cached: 1 ✔
[e3/04be0b] process > mod:rVersions                          [100%] 1 of 1, cached: 1 ✔
[43/a6c713] process > mod:getParams                          [100%] 1 of 1, cached: 1 ✔
[b8/e5f19b] process > mod:makeModReport (1)                  [  0%] 0 of 1
[db/ccb474] process > mod:publish_modbase (24)               [100%] 24 of 24, cached: 24
[-        ] process > report                                 -
[ca/ed750a] process > publish (1)                            [100%] 2 of 2, cached: 2
Searching input for [.bam, .ubam] files.
Searching input for [.bam, .ubam] files.
Error executing process > 'mod:makeModReport (1)'

Caused by:
  Process `mod:makeModReport (1)` terminated with an error exit status (1)

Command executed:

  workflow-glue report_mod \
      B3_CvT_chr1.wf-somatic-mod-report.html \
      --normal_summary normal_summary/ \
      --tumor_summary tumor_summary/ \
      --dml DML/ \
      --dmr DMR/ \
      --reference_fai ref.fa.fai \
      --sample_name B3_CvT_chr1 \
      --versions versions.txt \
      --params params.json --genome hg38  \
      --workflow_version v1.3.1

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
executor >  slurm (1)
[33/e06dff] process > index_ref_fai (1)                      [100%] 1 of 1, cached: 1 ✔
[b6/b0d8e4] process > cram_cache (1)                         [100%] 1 of 1, cached: 1 ✔
[16/281675] process > getVersions                            [100%] 1 of 1, cached: 1 ✔
[7f/f005f3] process > getVersions_somvar                     [100%] 1 of 1, cached: 1 ✔
[1b/e32d8e] process > getParams                              [100%] 1 of 1, cached: 1 ✔
[f9/fda36d] process > ingress_normal:checkBamHeaders (1)     [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:sortBam                 -
[-        ] process > ingress_normal:mergeBams               -
[-        ] process > ingress_normal:catSortBams             -
[c9/829b50] process > ingress_normal:validateIndex (1)       [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:samtools_index          -
[8c/4a0972] process > ingress_normal:check_for_alignment (1) [100%] 1 of 1, cached: 1 ✔
[93/d9af88] process > ingress_normal:minimap2_alignment (1)  [100%] 1 of 1, cached: 1 ✔
[e8/a8c58e] process > ingress_tumor:checkBamHeaders (1)      [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_tumor:sortBam                  -
[-        ] process > ingress_tumor:mergeBams                -
[-        ] process > ingress_tumor:catSortBams              -
[54/5c8f0e] process > ingress_tumor:validateIndex (1)        [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_tumor:samtools_index           -
[44/d402d9] process > ingress_tumor:check_for_alignment (1)  [100%] 1 of 1, cached: 1 ✔
[17/37132c] process > ingress_tumor:minimap2_alignment (1)   [100%] 1 of 1, cached: 1 ✔
[73/228f6c] process > getGenome (1)                          [100%] 2 of 2, cached: 2 ✔
[c9/37fb0e] process > getAllChromosomesBed (1)               [100%] 1 of 1, cached: 1 ✔
[c6/aaefbf] process > alignment_stats:bamstats (2)           [100%] 2 of 2, cached: 2 ✔
[af/c30e2f] process > alignment_stats:mosdepth (2)           [100%] 2 of 2, cached: 2 ✔
[ad/5806b9] process > alignment_stats:makeQCreport (1)       [100%] 1 of 1, cached: 1 ✔
[7e/239141] process > get_coverage (2)                       [100%] 2 of 2, cached: 2 ✔
[f6/cc58c7] process > publish_qc (17)                        [100%] 17 of 17, cached: 17 ✔
[a2/e1f00a] process > mod:validate_modbam (1)                [100%] 2 of 2, cached: 2 ✔
[e4/b17c10] process > mod:sample_probs (1)                   [100%] 2 of 2, cached: 2 ✔
[98/a88384] process > mod:modkit (1)                         [100%] 2 of 2, cached: 2 ✔
[6e/542e42] process > mod:concat_bedmethyl (1)               [100%] 2 of 2, cached: 2 ✔
[84/17f625] process > mod:bedmethyl_split (2)                [100%] 2 of 2, cached: 2 ✔
[4f/15beff] process > mod:summary (2)                        [100%] 2 of 2, cached: 2 ✔
[96/222728] process > mod:bed2dss (6)                        [100%] 6 of 6, cached: 6 ✔
[7c/db7931] process > mod:dss (3)                            [100%] 3 of 3, cached: 3 ✔
[fd/15c0b6] process > mod:getVersions                        [100%] 1 of 1, cached: 1 ✔
[e3/04be0b] process > mod:rVersions                          [100%] 1 of 1, cached: 1 ✔
[43/a6c713] process > mod:getParams                          [100%] 1 of 1, cached: 1 ✔
[b8/e5f19b] process > mod:makeModReport (1)                  [100%] 1 of 1, failed: 1 ✘
[db/ccb474] process > mod:publish_modbase (24)               [100%] 24 of 24, cached: 24 ✔
[-        ] process > report                                 [  0%] 0 of 1
[ca/ed750a] process > publish (1)                            [100%] 2 of 2, cached: 2
Searching input for [.bam, .ubam] files.
Searching input for [.bam, .ubam] files.
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'mod:makeModReport (1)'

Caused by:
  Process `mod:makeModReport (1)` terminated with an error exit status (1)

Command executed:

  workflow-glue report_mod \
      B3_CvT_chr1.wf-somatic-mod-report.html \
      --normal_summary normal_summary/ \
      --tumor_summary tumor_summary/ \
      --dml DML/ \
      --dmr DMR/ \
      --reference_fai ref.fa.fai \
      --sample_name B3_CvT_chr1 \
      --versions versions.txt \
      --params params.json --genome hg38  \
      --workflow_version v1.3.1

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
executor >  slurm (1)
[33/e06dff] process > index_ref_fai (1)                      [100%] 1 of 1, cached: 1 ✔
[b6/b0d8e4] process > cram_cache (1)                         [100%] 1 of 1, cached: 1 ✔
[16/281675] process > getVersions                            [100%] 1 of 1, cached: 1 ✔
[7f/f005f3] process > getVersions_somvar                     [100%] 1 of 1, cached: 1 ✔
[1b/e32d8e] process > getParams                              [100%] 1 of 1, cached: 1 ✔
[f9/fda36d] process > ingress_normal:checkBamHeaders (1)     [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:sortBam                 -
[-        ] process > ingress_normal:mergeBams               -
[-        ] process > ingress_normal:catSortBams             -
[c9/829b50] process > ingress_normal:validateIndex (1)       [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_normal:samtools_index          -
[8c/4a0972] process > ingress_normal:check_for_alignment (1) [100%] 1 of 1, cached: 1 ✔
[93/d9af88] process > ingress_normal:minimap2_alignment (1)  [100%] 1 of 1, cached: 1 ✔
[e8/a8c58e] process > ingress_tumor:checkBamHeaders (1)      [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_tumor:sortBam                  -
[-        ] process > ingress_tumor:mergeBams                -
[-        ] process > ingress_tumor:catSortBams              -
[54/5c8f0e] process > ingress_tumor:validateIndex (1)        [100%] 1 of 1, cached: 1 ✔
[-        ] process > ingress_tumor:samtools_index           -
[44/d402d9] process > ingress_tumor:check_for_alignment (1)  [100%] 1 of 1, cached: 1 ✔
[17/37132c] process > ingress_tumor:minimap2_alignment (1)   [100%] 1 of 1, cached: 1 ✔
[73/228f6c] process > getGenome (1)                          [100%] 2 of 2, cached: 2 ✔
[c9/37fb0e] process > getAllChromosomesBed (1)               [100%] 1 of 1, cached: 1 ✔
[c6/aaefbf] process > alignment_stats:bamstats (2)           [100%] 2 of 2, cached: 2 ✔
[af/c30e2f] process > alignment_stats:mosdepth (2)           [100%] 2 of 2, cached: 2 ✔
[ad/5806b9] process > alignment_stats:makeQCreport (1)       [100%] 1 of 1, cached: 1 ✔
[7e/239141] process > get_coverage (2)                       [100%] 2 of 2, cached: 2 ✔
[f6/cc58c7] process > publish_qc (17)                        [100%] 17 of 17, cached: 17 ✔
[a2/e1f00a] process > mod:validate_modbam (1)                [100%] 2 of 2, cached: 2 ✔
[e4/b17c10] process > mod:sample_probs (1)                   [100%] 2 of 2, cached: 2 ✔
[98/a88384] process > mod:modkit (1)                         [100%] 2 of 2, cached: 2 ✔
[6e/542e42] process > mod:concat_bedmethyl (1)               [100%] 2 of 2, cached: 2 ✔
[84/17f625] process > mod:bedmethyl_split (2)                [100%] 2 of 2, cached: 2 ✔
[4f/15beff] process > mod:summary (2)                        [100%] 2 of 2, cached: 2 ✔
[96/222728] process > mod:bed2dss (6)                        [100%] 6 of 6, cached: 6 ✔
[7c/db7931] process > mod:dss (3)                            [100%] 3 of 3, cached: 3 ✔
[fd/15c0b6] process > mod:getVersions                        [100%] 1 of 1, cached: 1 ✔
[e3/04be0b] process > mod:rVersions                          [100%] 1 of 1, cached: 1 ✔
[43/a6c713] process > mod:getParams                          [100%] 1 of 1, cached: 1 ✔
[b8/e5f19b] process > mod:makeModReport (1)                  [100%] 1 of 1, failed: 1 ✘
[db/ccb474] process > mod:publish_modbase (24)               [100%] 24 of 24, cached: 24 ✔
[-        ] process > report                                 [  0%] 0 of 1
[ca/ed750a] process > publish (1)                            [100%] 2 of 2, cached: 2
Searching input for [.bam, .ubam] files.
Searching input for [.bam, .ubam] files.
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'mod:makeModReport (1)'

Caused by:
  Process `mod:makeModReport (1)` terminated with an error exit status (1)

Command executed:

  workflow-glue report_mod \
      B3_CvT_chr1.wf-somatic-mod-report.html \
      --normal_summary normal_summary/ \
      --tumor_summary tumor_summary/ \
      --dml DML/ \
      --dmr DMR/ \
      --reference_fai ref.fa.fai \
      --sample_name B3_CvT_chr1 \
      --versions versions.txt \
      --params params.json --genome hg38  \
      --workflow_version v1.3.1

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
  [15:55:42 - workflow_glue] Bootstrapping CLI.
  [15:55:51 - workflow_glue] Starting entrypoint.
  [15:55:51 - workflow_glue.report_mod] Load: ref.fa.fai
  [15:55:52 - workflow_glue.report_mod] Load: tumor_summary/
  [15:55:52 - workflow_glue.report_mod] Load: normal_summary/
  [15:55:52 - workflow_glue.report_mod] Load: DML/
  [15:55:52 - workflow_glue.report_mod] Load: DMR/
  Traceback (most recent call last):
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
      return self._engine.get_loc(casted_key)
    File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'mod'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/home/dejlu879/.nextflow/assets/epi2me-labs/wf-somatic-variation/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/dejlu879/.nextflow/assets/epi2me-labs/wf-somatic-variation/bin/workflow_glue/__init__.py", line 82, in cli
      args.func(args)
    File "/home/dejlu879/.nextflow/assets/epi2me-labs/wf-somatic-variation/bin/workflow_glue/report_mod.py", line 205, in main
      (tumor_df["sample"] == args.sample_name) & (tumor_df["mod"] != "C"),
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
      indexer = self.columns.get_loc(key)
    File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
      raise KeyError(key) from err
  KeyError: 'mod'

Work dir:
  /weka/dejlu879/BEBIC/CellLineB/wf-sv_B3_CvT/chr1/work/b8/e5f19b20c7843b5522c1ae7f8aff58
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by RenzoTale88** [comment]
Hi @lucy924 would it be possibly for you to share the content of the files in:
```
/weka/dejlu879/BEBIC/CellLineB/wf-sv_B3_CvT/chr1/work/b8/e5f19b20c7843b5522c1ae7f8aff58/tumor_summary/
```

Thanks in advance
Andrea

**Comment by lucy924** [comment]
Sure
[tumor_summary.gz](https://github.com/user-attachments/files/16808608/tumor_summary.gz)

**Comment by RenzoTale88** [comment]
Thank you @lucy924 and apologies for the late reply. I'll have a look and try to reproduce the issue you are finding.

Andrea

**Comment by RenzoTale88** [comment]
@lucy924 I'm still investigating this issue. In the meanwhile, can you try using the latest version of the workflow (v1.4.0)? We released some fixes of modkit, and might be useful to know if you still come across the problem with the latest release.

**Comment by lucy924** [comment]
The problem seems to be gone now! 
(at least with the latest release and my current settings).
For reference, my custom.config is this:
```
process {
  withName: sample_probs {
    memory=32.GB
  }
  withName: summary {
    memory=120.GB
  }
}
```
But I'm glad it actually finished running!
Thank you!

**Comment by sh0rt2l0ng** [comment]
Also got this error with latest v1.4.0 workflow. Did we find out the root cause? 
![error](https://github.com/user-attachments/assets/e9756e3b-41a5-4dfe-a7ce-ff7313fa4983)

**Comment by sh0rt2l0ng** [comment]
BTW, how can we resume the stopped job as before? It seems I can't resume in new EPI2ME GUI once the job is stopped with error. Or can we resume the job via command line? Where can I find the exact nextflow command executed by the GUI here? Thanks.

**Comment by lucy924** [comment]
@sh0rt2l0ng I did not find out the root cause of this problem, it just stopped happening with that particular run. I don't know if it will pop up in the future though, and will investigate more if I come across it, it's just not a priority for me right now. Would love to know the answer too!
